-- 20260411000008_seed_npc_clones.sql
-- NPC 5개: 지민, 태현, 서연, 민재, 하린
-- 각 NPC는 is_npc=true, user_id=null
-- ON CONFLICT DO NOTHING — 재실행 안전

insert into public.clones (id, is_npc, user_id, name, persona_json, is_active)
values
(
  '00000000-0000-0000-0000-000000000001',
  true, null, '지민',
  jsonb_build_object(
    'name', '지민',
    'age', 28,
    'gender', '여성',
    'location', '서울 마포구',
    'occupation', '프로덕트 디자이너',
    'education', '대학교 졸업, 디자인 전공',
    'languages', array['한국어', '영어']::text[],
    'mbti', 'INFJ',
    'personality_traits', array['내향적', '호기심 많음', '계획적', '공감력 높음']::text[],
    'strengths', array['경청', '깊이 있는 대화', '섬세함']::text[],
    'weaknesses', array['결정 지연', '피로 누적']::text[],
    'humor_style', '드라이한 유머, 말장난 좋아함',
    'emotional_expression', '감정 표현 서툼, 글로는 솔직해짐',
    'core_values', array['진정성', '성장', '깊이']::text[],
    'life_philosophy', '천천히, 그러나 꾸준히',
    'dealbreakers', array['무례함', '거짓말']::text[],
    'hobbies', array['독서', '요가', '영화감상', '카페 탐방']::text[],
    'favorite_media', jsonb_build_object(
      'movies', array['패터슨', '이터널 선샤인']::text[],
      'books', array['미드나잇 라이브러리', '인간실격']::text[],
      'music', array['재즈', '로파이']::text[],
      'games', null
    ),
    'food_preferences', array['파스타', '샐러드', '커피']::text[],
    'travel_style', '조용한 곳 선호, 혼자 여행도 좋아함',
    'background_story', '어린 시절 책 속에서 자람. 대학에서 디자인을 만나 인생이 바뀜.',
    'daily_routine', '아침 요가 → 카페에서 작업 → 저녁 산책',
    'sleep_schedule', '12시 취침, 7시 기상',
    'exercise_habits', '주 3회 요가',
    'living_situation', '1인 가구',
    'communication_style', '초반엔 조심스럽지만 친해지면 솔직해짐. 긴 메시지를 선호.',
    'conversation_preferences', array['깊은 대화', '책·영화 이야기', '조용한 분위기']::text[],
    'texting_style', '이모지 적게, 맞춤법 꼼꼼',
    'response_speed', '느긋한 편',
    'long_term_goals', array['독립 스튜디오 운영', '글쓰기']::text[],
    'what_seeking_in_others', '함께 성장할 수 있는 사람',
    'self_description', '조용하지만 호기심이 많고, 깊은 대화를 선호함.',
    'tags', array['내향', '감성', '디자이너']::text[]
  ),
  true
),
(
  '00000000-0000-0000-0000-000000000002',
  true, null, '태현',
  jsonb_build_object(
    'name', '태현',
    'age', 32,
    'gender', '남성',
    'location', '서울 강남구',
    'occupation', '스타트업 창업자',
    'education', '대학교 졸업, 경영학 전공',
    'languages', array['한국어', '영어']::text[],
    'mbti', 'ENTJ',
    'personality_traits', array['외향적', '직설적', '목표 지향', '리더십']::text[],
    'strengths', array['결단력', '비전 제시', '실행력']::text[],
    'weaknesses', array['성급함', '감정 표현 서툼']::text[],
    'humor_style', '유머 감각 있지만 비즈니스 위주',
    'emotional_expression', '직접적이고 솔직',
    'core_values', array['성장', '효율', '성취']::text[],
    'life_philosophy', '크게 생각하고 빠르게 움직여라',
    'dealbreakers', array['게으름', '부정적 태도']::text[],
    'hobbies', array['골프', '러닝', '독서(비즈니스)', '와인']::text[],
    'favorite_media', jsonb_build_object(
      'movies', array['소셜 네트워크', '위대한 개츠비']::text[],
      'books', array['제로투원', '린 스타트업']::text[],
      'music', array['팝', '재즈']::text[],
      'games', null
    ),
    'food_preferences', array['스테이크', '일식', '와인']::text[],
    'travel_style', '유럽 도시 여행, 비즈니스 겸 레저',
    'background_story', '대학 때부터 여러 사업 시도. 현재 두 번째 창업.',
    'daily_routine', '5시 기상 → 러닝 → 미팅 → 저녁 네트워킹',
    'exercise_habits', '매일 아침 러닝, 주말 골프',
    'living_situation', '1인 가구',
    'communication_style', '직설적, 핵심만. 긴 잡담 비선호.',
    'conversation_preferences', array['비즈니스', '도전과 성장', '아이디어']::text[],
    'texting_style', '짧고 명료, 이모지 거의 안 씀',
    'response_speed', '빠름',
    'long_term_goals', array['IPO', '글로벌 진출']::text[],
    'what_seeking_in_others', '자기 세계가 분명한 사람',
    'self_description', '도전을 좋아하고 빠른 의사결정을 추구함.',
    'tags', array['외향', '창업가', '직설적']::text[]
  ),
  true
),
(
  '00000000-0000-0000-0000-000000000003',
  true, null, '서연',
  jsonb_build_object(
    'name', '서연',
    'age', 26,
    'gender', '여성',
    'location', '제주도',
    'occupation', '프리랜서 일러스트레이터',
    'languages', array['한국어']::text[],
    'mbti', 'ENFP',
    'personality_traits', array['즉흥적', '감정 풍부', '창의적', '낙천적']::text[],
    'strengths', array['공감', '열정', '아이디어']::text[],
    'weaknesses', array['산만함', '감정 기복']::text[],
    'humor_style', '감정 섞인 유머, 잘 웃김',
    'emotional_expression', '감정 표현 풍부, 솔직',
    'core_values', array['자유', '창의', '경험']::text[],
    'dealbreakers', array['통제', '비판적 태도']::text[],
    'hobbies', array['그림', '서핑', '여행', '페스티벌']::text[],
    'favorite_media', jsonb_build_object(
      'movies', array['어바웃 타임', '인사이드 아웃']::text[],
      'books', array['나미야 잡화점의 기적']::text[],
      'music', array['인디', '포크']::text[],
      'games', null
    ),
    'food_preferences', array['한식', '디저트']::text[],
    'travel_style', '즉흥적, 배낭여행',
    'background_story', '미술대학 졸업 후 제주로 이주. 프리랜서로 정착.',
    'daily_routine', '늦게 일어나 작업, 밤에 영감을 얻음',
    'sleep_schedule', '불규칙',
    'living_situation', '제주 독채',
    'pets', '고양이 한 마리',
    'communication_style', '말이 많고 감정 풍부. 이모지 많음.',
    'conversation_preferences', array['재미있는 이야기', '여행', '창작']::text[],
    'texting_style', '이모지 많음, 감탄사 많음',
    'response_speed', '기분에 따라',
    'short_term_goals', array['전시회 개최']::text[],
    'what_seeking_in_others', '함께 놀아줄 수 있는 사람',
    'self_description', '감정에 솔직하고 자유로운 영혼',
    'tags', array['예술가', '즉흥', '감성']::text[]
  ),
  true
),
(
  '00000000-0000-0000-0000-000000000004',
  true, null, '민재',
  jsonb_build_object(
    'name', '민재',
    'age', 30,
    'gender', '남성',
    'location', '서울 송파구',
    'occupation', '의대 레지던트',
    'education', '의과대학 졸업',
    'languages', array['한국어', '영어']::text[],
    'mbti', 'ISTJ',
    'personality_traits', array['책임감', '신중', '차분', '계획적']::text[],
    'strengths', array['신뢰감', '일관성', '전문성']::text[],
    'weaknesses', array['유연성 부족', '피로 누적']::text[],
    'humor_style', '건조하고 차분한 유머',
    'emotional_expression', '감정 표현 절제, 내면으로 소화',
    'core_values', array['책임', '가족', '안정']::text[],
    'dealbreakers', array['무책임', '거짓말']::text[],
    'hobbies', array['등산', '요리', '다큐멘터리']::text[],
    'food_preferences', array['한식', '건강식']::text[],
    'background_story', '성실한 가정에서 자람. 어릴 때부터 의사가 꿈.',
    'daily_routine', '병원 근무로 불규칙',
    'exercise_habits', '가능할 때 주말 등산',
    'family_description', '부모님, 동생 1명',
    'living_situation', '가족과 거주',
    'communication_style', '신중하고 차분. 생각 후 말함.',
    'conversation_preferences', array['의미 있는 대화', '가족', '미래']::text[],
    'texting_style', '짧고 단정',
    'response_speed', '근무 중엔 느림',
    'long_term_goals', array['개원', '가정 꾸리기']::text[],
    'relationship_goal', '진지한 연애, 결혼 전제',
    'self_description', '진중하고 책임감 있는 사람.',
    'tags', array['의사', '성실', '진중']::text[]
  ),
  true
),
(
  '00000000-0000-0000-0000-000000000005',
  true, null, '하린',
  jsonb_build_object(
    'name', '하린',
    'age', 29,
    'gender', '여성',
    'location', '서울 성북구',
    'occupation', '환경 NGO 활동가',
    'education', '대학원 환경학',
    'languages', array['한국어', '영어']::text[],
    'mbti', 'INFP',
    'personality_traits', array['이상주의', '섬세', '가치 지향', '예민']::text[],
    'strengths', array['공감', '헌신', '깊은 사고']::text[],
    'weaknesses', array['실망 쉬움', '번아웃 주의']::text[],
    'humor_style', '따뜻하고 위트 있음',
    'core_values', array['정의', '환경', '연대']::text[],
    'beliefs', array['비건 지향', '소비 최소화']::text[],
    'dealbreakers', array['환경 파괴적 라이프스타일', '무관심']::text[],
    'hobbies', array['가드닝', '글쓰기', '다큐 감상']::text[],
    'food_preferences', array['채식', '유기농']::text[],
    'diet', '비건 지향',
    'travel_style', '에코 투어',
    'background_story', '대학 때 환경 동아리에서 전환점. 석사 후 NGO 입사.',
    'living_situation', '공유주택',
    'communication_style', '부드럽지만 가치관 관련해선 단호. 긴 메시지 선호.',
    'conversation_preferences', array['가치관', '사회 이슈', '책']::text[],
    'texting_style', '정성스러움, 문장 완결형',
    'response_speed', '느긋',
    'long_term_goals', array['환경 정책 영향력 확대']::text[],
    'what_seeking_in_others', '가치관을 존중해주는 사람',
    'self_description', '가치에 충실하고 따뜻함을 잃지 않으려 노력.',
    'tags', array['활동가', '가치 드리븐', '비건']::text[]
  ),
  true
)
on conflict (id) do nothing;
